name: tests-server

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for all branches
  ## Default Activity Type: 'opened', 'synchronize', 'reopened'
  pull_request:
    # If files changed directly inside the path as below
    paths:
      - 'server/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: cd server && npm ci && npm run test:ci